SET @date_threshold = 86400 * 90;
SET @yyyy_mm_dd=DATE_FORMAT(now(),'%Y%m%d');

SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swtickets_',  @yyyy_mm_dd, '` LIKE `swtickets`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketpostlocks_',  @yyyy_mm_dd, '` LIKE `swticketpostlocks`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketlocks_',  @yyyy_mm_dd, '` LIKE `swticketlocks`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketlinkchains_',  @yyyy_mm_dd, '` LIKE `swticketlinkchains`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketfollowups_',  @yyyy_mm_dd, '` LIKE `swticketfollowups`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketdrafts_',  @yyyy_mm_dd, '` LIKE `swticketdrafts`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swescalationpaths_',  @yyyy_mm_dd, '` LIKE `swescalationpaths`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketnotes_',  @yyyy_mm_dd, '` LIKE `swticketnotes`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketauditlogs_',  @yyyy_mm_dd, '` LIKE `swticketauditlogs`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketlinkedtables_',  @yyyy_mm_dd, '` LIKE `swticketlinkedtables`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketlinks_',  @yyyy_mm_dd, '` LIKE `swticketlinks`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketmergelog_',  @yyyy_mm_dd, '` LIKE `swticketmergelog`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketmessageids_',  @yyyy_mm_dd, '` LIKE `swticketmessageids`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketposts_',  @yyyy_mm_dd, '` LIKE `swticketposts`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swticketwatchers_',  @yyyy_mm_dd, '` LIKE `swticketwatchers`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swtickettimetracks_',  @yyyy_mm_dd, '` LIKE `swtickettimetracks`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swattachments_',  @yyyy_mm_dd, '` LIKE `swattachments`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swcustomfieldvalues_',  @yyyy_mm_dd, '` LIKE `swcustomfieldvalues`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swparserlogs_',  @yyyy_mm_dd, '` LIKE `swparserlogs`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('CREATE TABLE IF NOT EXISTS `backup_swparserlogdata_',  @yyyy_mm_dd, '` LIKE `swparserlogdata`'); PREPARE stmt from @sql; EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = CONCAT('INSERT INTO `backup_swtickets_',  @yyyy_mm_dd, '` SELECT * FROM `swtickets` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketpostlocks_',  @yyyy_mm_dd, '` SELECT * FROM `swticketpostlocks` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketlocks_',  @yyyy_mm_dd, '` SELECT * FROM `swticketlocks` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketlinkchains_',  @yyyy_mm_dd, '` SELECT * FROM `swticketlinkchains` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketfollowups_',  @yyyy_mm_dd, '` SELECT * FROM `swticketfollowups` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketdrafts_',  @yyyy_mm_dd, '` SELECT * FROM `swticketdrafts` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swescalationpaths_',  @yyyy_mm_dd, '` SELECT * FROM `swescalationpaths` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketnotes_',  @yyyy_mm_dd, '` SELECT * FROM `swticketnotes` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketauditlogs_',  @yyyy_mm_dd, '` SELECT * FROM `swticketauditlogs` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketlinkedtables_',  @yyyy_mm_dd, '` SELECT * FROM `swticketlinkedtables` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketlinks_',  @yyyy_mm_dd, '` SELECT * FROM `swticketlinks` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketmergelog_',  @yyyy_mm_dd, '` SELECT * FROM `swticketmergelog` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketmessageids_',  @yyyy_mm_dd, '` SELECT * FROM `swticketmessageids` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketposts_',  @yyyy_mm_dd, '` SELECT * FROM `swticketposts` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swticketwatchers_',  @yyyy_mm_dd, '` SELECT * FROM `swticketwatchers` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swtickettimetracks_',  @yyyy_mm_dd, '` SELECT * FROM `swtickettimetracks` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swattachments_',  @yyyy_mm_dd, '` SELECT * FROM `swattachments` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swcustomfieldvalues_',  @yyyy_mm_dd, '` SELECT * FROM `swcustomfieldvalues` WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold)'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swparserlogs_',  @yyyy_mm_dd, '` SELECT * FROM `swparserlogs`'); PREPARE stmt from @sql; EXECUTE stmt;
SET @sql = CONCAT('INSERT INTO `backup_swparserlogdata_',  @yyyy_mm_dd, '` SELECT * FROM `swparserlogdata`'); PREPARE stmt from @sql; EXECUTE stmt;
DEALLOCATE PREPARE stmt;

DELETE FROM swtickets 			 WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketpostlocks 	 WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketlocks        WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketlinkchains	 WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketfollowups    WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketdrafts       WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swescalationpaths    WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketnotes        WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketauditlogs    WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketlinkedtables WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketlinks        WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketmergelog     WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketmessageids   WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketposts        WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swticketwatchers     WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swtickettimetracks   WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swattachments        WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
DELETE FROM swcustomfieldvalues  WHERE (dateline < UNIX_TIMESTAMP(NOW()) - @date_threshold);
TRUNCATE swparserlogs;
TRUNCATE swparserlogdata;

